services:
    sonata.admin.product:
        class: PolcodeProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Products", label: "Product" }
        arguments:
            - ~
            - PolcodeProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
            
            
    sonata.admin.category:
        class: PolcodeProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Categories", label: "Category" }
        arguments:
            - ~
            - PolcodeProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]