polcode_product:
    type: annotation
    resource: @PolcodeProductBundle/Controller/DefaultController.php
    
polcode_product_controller:
    type: annotation
    resource: @PolcodeProductBundle/Controller/ProductAdminController.php

api_get_users:
    pattern: /crud
    defaults: { _controller: PolcodeProductBundle:ProductAdminController:index, name: null, _format: json }
    methods: [GET]
    